<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="D:/IdeaProject/interfaceRestAssured(failed)"
           tests="3"
           failures="3"
           errors="0"
           skipped="0"
           time="0.011">
  <properties />
            <testcase name="TestAssertW" time="0.003" classname="TestNg.TestAssert">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  TestNg.TestAssert.TestAssertW(TestAssert.java:25)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  suit.RunSuit.main(RunSuit.java:28)
]]>
      </failure>

          </testcase>
            <testcase name="TestAssertnew" time="0.004" classname="TestNg.TestAssert">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	两者不相等 expected [13] but found [12]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	两者不相等 expected [13] but found [12]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  TestNg.TestAssert.TestAssertnew(TestAssert.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  suit.RunSuit.main(RunSuit.java:28)
]]>
      </failure>

          </testcase>
            <testcase name="TestAssert" time="0.004" classname="TestNg.TestAssert">
                <failure type="java.lang.AssertionError"
                  message="expected [2] but found [2]"
              >
<![CDATA[java.lang.AssertionError: expected [2] but found [2]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:179)
  TestNg.TestAssert.TestAssert(TestAssert.java:10)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  suit.RunSuit.main(RunSuit.java:28)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
